In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from google.colab import files
uploaded=files.upload()

data=pd.read_csv("dataset2.csv")

Saving dataset2.csv to dataset2.csv

In [ ]:
data.head(2)

,Patient ID,Age,Blood Pressure,Urine Specific Gravity,Albumin in urine,Sugar in urine,RBC,Puss cells,Pus cells clumps,Bacteria,...,Urea in blood,Serum Creatinine,Sodium in blood,Potassium in blood,Hemoglobin,Packed corpuscular volume,WBC count,RBC count,Apetite,Chronic kidney failure
0,0,48,178,10.10,2.0,2,abnormal,abnormal,present,present,...,195.0,9.08,124.0,6.0,8.0,25.0,11319,3.8,poor,yes
1,1,7,138,10.14,1.0,4,abnormal,abnormal,present,present,...,111.0,7.88,133.0,6.8,11.0,27.0,11018,2.9,poor,yes

s=pd.Series(data= NaN, index=[49,48,47,1,2,3,4,9])
here the indixes that we have assigned are called labels. labels are also associated with the original indices values of the list.

s.iloc[:3]: slice first 3 rows. refers default index values which start with zero.. of series(not of labels)
s.loc[:3]: slice upto and including. it traverses through the series until the index value doesn't match the label value (i.e till 3)

series mein... slicing operation on LABELS(user defined indices) happens from START TO END LABEL (in index it happens from start to end-1 index.)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15051 entries, 0 to 15050
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Patient ID                 15051 non-null  int64
 1   Age                        15051 non-null  int64
 2   Blood Pressure             15051 non-null  int64
 3   Urine Specific Gravity     15051 non-null  float64
 4   Albumin in urine           15051 non-null  float64
 5   Sugar in urine             15051 non-null  int64
 6   RBC                        15051 non-null  object
 7   Puss cells                 15051 non-null  object
 8   Pus cells clumps           15042 non-null  object
 9   Bacteria                   15045 non-null  object
 10  Random blood glucose       15051 non-null  int64
 11  Urea in blood              15051 non-null  float64
 12  Serum Creatinine           15042 non-null  float64
 13  Sodium in blood            15051 non-null  float64
 14  Potassium in blood         15051 non-null  float64
 15  Hemoglobin                 15051 non-null  float64
 16  Packed corpuscular volume  15051 non-null  float64
 17  WBC count                  15051 non-null  int64
 18  RBC count                  15051 non-null  float64
 19  Apetite                    15050 non-null  object
 20  Chronic kidney failure     15049 non-null  object
dtypes: float64(9), int64(6), object(6)
memory usage: 2.4+ MB

In [ ]:
data.shape

(15051, 21)

In [ ]:
data.describe()

,Patient ID,Age,Blood Pressure,Urine Specific Gravity,Albumin in urine,Sugar in urine,Random blood glucose,Urea in blood,Serum Creatinine,Sodium in blood,Potassium in blood,Hemoglobin,Packed corpuscular volume,WBC count,RBC count
count,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15042.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.00000
mean,7525.000000,52.100458,93.232144,11.287820,228.358714,154.320710,157.608132,59.652501,3.224108,138.584739,5.384616,11.999568,36.842961,7624.345160,4.38249
std,4344.993786,17.554229,19.906447,1.522975,314.218358,248.575959,62.352270,42.514865,5.479592,5.823178,0.859756,2.410039,7.394153,2250.210113,1.02287
min,0.000000,2.000000,50.000000,10.000000,0.000000,0.000000,70.000000,10.000000,0.400000,120.000000,3.500000,6.000000,20.000000,3044.000000,2.50000
25%,3762.500000,45.000000,80.000000,10.190000,0.000000,0.000000,105.000000,25.000000,0.932500,135.000000,4.790000,10.000000,30.500000,5691.000000,3.50000
50%,7525.000000,55.000000,94.000000,10.240000,1.000000,1.000000,139.000000,40.000000,1.400000,139.000000,5.400000,12.000000,36.000000,7628.000000,4.50000
75%,11287.500000,65.000000,107.000000,12.350000,452.400000,200.000000,208.000000,93.550000,3.250000,143.000000,6.090000,14.000000,43.000000,9505.000000,5.30000
max,15050.000000,90.000000,180.000000,15.000000,989.900000,1000.000000,300.000000,200.000000,76.000000,150.000000,7.500000,16.000000,50.000000,11999.000000,6.00000

In [ ]:
data['RBC count']

0        3.8
1        2.9
2        4.4
3        3.2
4        3.9
        ...
15046    3.5
15047    3.2
15048    3.7
15049    3.8
15050    4.2
Name: RBC count, Length: 15051, dtype: float64

In [ ]:
data.loc[374, 'Urea in blood']

np.float64(33.0)

In [ ]:
data.iloc[12, 8]

'present'

See if any null values are present. Display count of null values.

In [ ]:
data.isnull()

,Patient ID,Age,Blood Pressure,Urine Specific Gravity,Albumin in urine,Sugar in urine,RBC,Puss cells,Pus cells clumps,Bacteria,...,Urea in blood,Serum Creatinine,Sodium in blood,Potassium in blood,Hemoglobin,Packed corpuscular volume,WBC count,RBC count,Apetite,Chronic kidney failure
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15046,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15047,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15048,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15049,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15050,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
print(data.isnull().sum())

Patient ID                   0
Age                          0
Blood Pressure               0
Urine Specific Gravity       0
Albumin in urine             0
Sugar in urine               0
RBC                          0
Puss cells                   0
Pus cells clumps             9
Bacteria                     6
Random blood glucose         0
Urea in blood                0
Serum Creatinine             9
Sodium in blood              0
Potassium in blood           0
Hemoglobin                   0
Packed corpuscular volume    0
WBC count                    0
RBC count                    0
Apetite                      1
Chronic kidney failure       2
dtype: int64

therefore, there are total 27 missing values.

replacing missing values with mean.

In [4]:
data['Pus cells clumps'].fillna(data['Pus cells clumps'].mode()[0], inplace=True)

/tmp/ipykernel_3283/888069267.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Pus cells clumps'].fillna(data['Pus cells clumps'].mode()[0], inplace=True)

In [ ]:
print(data.isnull().sum())

Patient ID                   0
Age                          0
Blood Pressure               0
Urine Specific Gravity       0
Albumin in urine             0
Sugar in urine               0
RBC                          0
Puss cells                   0
Pus cells clumps             0
Bacteria                     0
Random blood glucose         0
Urea in blood                0
Serum Creatinine             0
Sodium in blood              0
Potassium in blood           0
Hemoglobin                   0
Packed corpuscular volume    0
WBC count                    0
RBC count                    0
Apetite                      0
Chronic kidney failure       0
dtype: int64

In [5]:
data['Bacteria'].fillna(data['Bacteria'].mode()[0], inplace=True)

/tmp/ipykernel_3283/2605330781.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Bacteria'].fillna(data['Bacteria'].mode()[0], inplace=True)

In [6]:
data['Serum Creatinine'].fillna(data['Serum Creatinine'].mean(), inplace=True)

/tmp/ipykernel_3283/2698678221.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Serum Creatinine'].fillna(data['Serum Creatinine'].mean(), inplace=True)

In [7]:
data['Apetite'].fillna(data['Apetite'].mode()[0], inplace=True)

/tmp/ipykernel_3283/348316318.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Apetite'].fillna(data['Apetite'].mode()[0], inplace=True)

In [8]:
data['Chronic kidney failure'].fillna(data['Chronic kidney failure'].mode()[0], inplace=True)

/tmp/ipykernel_3283/3897703642.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Chronic kidney failure'].fillna(data['Chronic kidney failure'].mode()[0], inplace=True)

ALL MISSING VALUES FILLED.

conditional filtering

In [ ]:
data[data['Blood Pressure']>170].head(5)

,Patient ID,Age,Blood Pressure,Urine Specific Gravity,Albumin in urine,Sugar in urine,RBC,Puss cells,Pus cells clumps,Bacteria,...,Urea in blood,Serum Creatinine,Sodium in blood,Potassium in blood,Hemoglobin,Packed corpuscular volume,WBC count,RBC count,Apetite,Chronic kidney failure
0,0,48,178,10.10,2.0,2,abnormal,abnormal,present,present,...,195.0,9.08,124.0,6.0,8.0,25.0,11319,3.8,poor,yes
4,4,51,175,10.15,4.0,5,abnormal,abnormal,present,present,...,152.0,7.32,132.0,6.8,9.0,30.0,3055,3.9,poor,yes
8,8,52,171,10.09,1.0,2,abnormal,abnormal,present,present,...,110.0,8.72,124.0,6.0,7.0,21.0,11243,4.1,poor,yes
17,17,47,177,10.10,2.0,4,abnormal,abnormal,present,present,...,45.0,10.77,126.0,6.2,8.0,24.0,9939,3.7,poor,yes
18,18,60,177,10.13,2.0,2,abnormal,abnormal,present,present,...,81.0,11.25,124.0,6.9,8.0,20.0,7033,3.8,poor,yes

In [ ]:
part= data[data['Sugar in urine']<180]
part[part['Sugar in urine']>60].value_counts().sum()

np.int64(2381)

In [ ]:
part2= part[part['Sugar in urine']>60]
part2['Sugar in urine'].value_counts().sum()

np.int64(2381)

In [ ]:
nan_rows = part2[part2.isnull().any(axis=1)]
display(nan_rows)

,Patient ID,Age,Blood Pressure,Urine Specific Gravity,Albumin in urine,Sugar in urine,RBC,Puss cells,Pus cells clumps,Bacteria,...,Urea in blood,Serum Creatinine,Sodium in blood,Potassium in blood,Hemoglobin,Packed corpuscular volume,WBC count,RBC count,Apetite,Chronic kidney failure
8383,8383,46,80,13.23,809.1,173,abnormal,normal,present,present,...,143.7,9.6,148.2,4.60,10.6,30.6,6538,4.41,poor,NaN
9719,9719,45,60,10.50,536.1,126,normal,normal,NaN,present,...,105.0,0.7,139.2,4.77,9.3,35.3,4287,3.59,good,no
10530,10530,54,70,14.96,638.4,171,abnormal,abnormal,present,NaN,...,145.8,0.6,134.5,5.55,11.7,25.3,3967,3.25,good,yes
10540,10540,45,60,12.81,276.5,179,abnormal,abnormal,NaN,present,...,142.5,0.7,137.5,4.80,10.7,33.0,5846,4.17,good,yes
11492,11492,54,70,14.76,624.7,155,abnormal,abnormal,present,NaN,...,119.1,0.6,131.3,5.65,8.2,27.6,9358,3.39,good,yes
11720,11720,61,90,10.08,630.8,145,abnormal,abnormal,absent,absent,...,56.9,NaN,127.9,5.29,9.8,26.5,11871,3.57,poor,yes
12464,12464,45,60,12.43,787.5,168,normal,normal,NaN,present,...,125.8,0.7,127.5,4.62,11.7,30.6,11085,3.24,good,no

In [ ]:
part2['Sugar in urine'].value_counts().sum()

np.int64(2381)

2381 patients have normal urine sugar levels.

In [ ]:
data.loc[5641, 'RBC count']

np.float64(5.1)

In [ ]:
data.iloc[::1000]

,Patient ID,Age,Blood Pressure,Urine Specific Gravity,Albumin in urine,Sugar in urine,RBC,Puss cells,Pus cells clumps,Bacteria,...,Urea in blood,Serum Creatinine,Sodium in blood,Potassium in blood,Hemoglobin,Packed corpuscular volume,WBC count,RBC count,Apetite,Chronic kidney failure
0,0,48,178,10.10,2.0,2,abnormal,abnormal,present,present,...,195.0,9.08,124.0,6.00,8.0,25.0,11319,3.80,poor,yes
1000,1000,8,117,10.22,0.0,1,normal,normal,absent,absent,...,40.0,0.60,144.0,3.60,16.0,40.0,8328,4.50,good,no
2000,2000,72,116,10.22,0.0,1,abnormal,abnormal,absent,absent,...,20.0,0.71,143.0,6.00,13.0,46.0,8783,5.00,poor,yes
3000,3000,59,101,10.18,1.0,1,abnormal,abnormal,absent,absent,...,10.0,0.90,136.0,4.10,14.0,47.0,5575,5.40,poor,yes
4000,4000,42,115,10.18,0.0,1,abnormal,abnormal,absent,absent,...,24.0,1.70,142.0,4.00,12.0,49.0,4199,5.80,poor,yes
5000,5000,14,100,10.23,1.0,0,normal,normal,absent,absent,...,37.0,1.80,141.0,3.50,16.0,49.0,9924,4.90,good,no
6000,6000,46,92,10.15,1.0,1,normal,normal,absent,absent,...,25.0,0.90,140.0,6.90,15.0,37.0,8849,4.80,good,no
7000,7000,68,116,10.17,1.0,1,abnormal,abnormal,present,present,...,38.0,1.40,136.0,6.50,12.0,37.0,6397,6.00,poor,yes
8000,8000,67,80,10.48,348.6,41,abnormal,abnormal,absent,absent,...,52.4,1.50,127.3,5.48,10.4,26.5,11532,3.67,poor,yes
9000,9000,59,70,14.96,200.1,133,abnormal,abnormal,absent,absent,...,112.9,15.00,139.7,6.06,11.9,25.3,8768,2.52,poor,yes
10000,10000,73,80,13.17,39.4,196,normal,normal,absent,absent,...,97.7,4.60,145.3,5.79,10.1,28.7,8505,4.25,good,no
11000,11000,71,90,11.29,734.4,61,abnormal,abnormal,present,present,...,131.7,4.40,128.3,4.86,11.7,32.0,10730,4.04,good,yes
12000,12000,70,90,11.94,751.6,168,abnormal,abnormal,absent,absent,...,114.2,4.00,132.3,5.48,11.3,33.5,4577,4.10,poor,yes
13000,13000,48,70,11.80,273.5,333,normal,normal,absent,absent,...,120.0,1.00,134.5,4.69,8.1,26.5,6356,2.71,good,no
14000,14000,8,60,13.73,592.6,178,normal,normal,absent,absent,...,44.8,0.90,132.6,5.87,10.5,25.6,3535,3.79,poor,no
15000,15000,60,90,13.99,138.0,64,normal,abnormal,absent,absent,...,89.3,1.10,130.7,6.28,11.5,29.0,6622,3.85,good,no

In [12]:
df1= data[(data['Age']==6) & (data['Chronic kidney failure']=='yes')]
df1[['Age', 'Apetite', 'Urea in blood', 'Chronic kidney failure']]

       Age Apetite  Urea in blood Chronic kidney failure
190      6    poor          200.0                    yes
2070     6    poor           27.0                    yes
3548     6    poor           23.0                    yes
7982     6    poor          103.5                    yes
9460     6    poor           44.1                    yes
10191    6    poor           50.0                    yes
10430    6    poor           78.3                    yes
11392    6    poor           58.3                    yes

there are 8 patients of 6 years of age. all the their apetite are poor.

In [13]:
df2= data[(data['Pus cells clumps']=='present') & (data['Chronic kidney failure']=='yes') & (data['Bacteria']=='present')]
df2[['Age', 'Puss cells', 'Bacteria', 'Pus cells clumps', 'Chronic kidney failure']].head(15)

    Age Puss cells Bacteria Pus cells clumps Chronic kidney failure
0    48   abnormal  present          present                    yes
1     7   abnormal  present          present                    yes
2    62   abnormal  present          present                    yes
3    48   abnormal  present          present                    yes
4    51   abnormal  present          present                    yes
5    60   abnormal  present          present                    yes
6    68   abnormal  present          present                    yes
7    24   abnormal  present          present                    yes
8    52   abnormal  present          present                    yes
9    53   abnormal  present          present                    yes
10   50   abnormal  present          present                    yes
11   63   abnormal  present          present                    yes
12   68   abnormal  present          present                    yes
13   68   abnormal  present          present                    yes
14   68   abnormal  present          present                    yes

all patients having pus cell clumps have abnormal amount of pus cells.

In [14]:
df3= data[(data['Hemoglobin']<13) & (data['Bacteria']=='present')]
df3[['Age', 'Hemoglobin', 'Bacteria', 'Chronic kidney failure']].head()

   Age  Hemoglobin Bacteria Chronic kidney failure
0   48         8.0  present                    yes
1    7        11.0  present                    yes
2   62         8.0  present                    yes
3   48        11.0  present                    yes
4   51         9.0  present                    yes

pateints having bacteria and low haemoglobin levels have vhronic kidney failure.

In [ ]:
data.columns

Index(['Patient ID', 'Age', 'Blood Pressure', 'Urine Specific Gravity',
       'Albumin in urine', 'Sugar in urine', 'RBC', 'Puss cells',
       'Pus cells clumps', 'Bacteria', 'Random blood glucose', 'Urea in blood',
       'Serum Creatinine', 'Sodium in blood', 'Potassium in blood',
       'Hemoglobin', 'Packed corpuscular volume', 'WBC count', 'RBC count',
       'Apetite', 'Chronic kidney failure'],
      dtype='object')

In [ ]:
data.groupby('Urea in blood').agg({'Sodium in blood':'mean'}).head()

               Sodium in blood
Urea in blood
10.0                140.103053
11.0                139.852000
12.0                139.608511
13.0                140.016736
14.0                140.239216

In [ ]:
data.groupby('Bacteria').agg({'Age':'mean'})

                Age
Bacteria
absent    51.626056
present   57.053313

for anemia risk:
ratio of Packed Corpuscular Volume to haemoglobin should be around 3. more or less then that is abnormal

In [9]:
data['PVC_Hb ratio']= data['Packed corpuscular volume']/data['Hemoglobin']
data['PVC_Hb ratio'].head()

0    3.125000
1    2.454545
2    3.375000
3    3.181818
4    3.333333
Name: PVC_Hb ratio, dtype: float64

In [10]:
data['Anemia risk']= np.where((data['PVC_Hb ratio']>2.7) & (data['PVC_Hb ratio']<3.3), 'low', 'high')
data['Anemia risk'].head()

0     low
1    high
2    high
3     low
4    high
Name: Anemia risk, dtype: object

In [ ]:
data.columns

Index(['Patient ID', 'Age', 'Blood Pressure', 'Urine Specific Gravity',
       'Albumin in urine', 'Sugar in urine', 'RBC', 'Puss cells',
       'Pus cells clumps', 'Bacteria', 'Random blood glucose', 'Urea in blood',
       'Serum Creatinine', 'Sodium in blood', 'Potassium in blood',
       'Hemoglobin', 'Packed corpuscular volume', 'WBC count', 'RBC count',
       'Apetite', 'Chronic kidney failure', 'PVC_Hb ratio', 'Anemia risk'],
      dtype='object')

In [11]:
r= data['PVC_Hb ratio'].corr(data['Random blood glucose'])
print(f'correlation btw pvc hb ratio and chronic kideny failure: {r}')

correlation btw pvc hb ratio and chronic kideny failure: -0.0029463553851239617

there is negligible correlation between pvc hb ratio and random blood sugar values.

In [17]:
data_concat = pd.concat([df3, df2], axis=1)
data_concat.head()

,Patient ID,Age,Blood Pressure,Urine Specific Gravity,Albumin in urine,Sugar in urine,RBC,Puss cells,Pus cells clumps,Bacteria,...,Sodium in blood,Potassium in blood,Hemoglobin,Packed corpuscular volume,WBC count,RBC count,Apetite,Chronic kidney failure,PVC_Hb ratio,Anemia risk
0,0.0,48.0,178.0,10.10,2.0,2.0,abnormal,abnormal,present,present,...,124.0,6.0,8.0,25.0,11319.0,3.8,poor,yes,3.125000,low
1,1.0,7.0,138.0,10.14,1.0,4.0,abnormal,abnormal,present,present,...,133.0,6.8,11.0,27.0,11018.0,2.9,poor,yes,2.454545,high
2,2.0,62.0,165.0,10.14,2.0,5.0,abnormal,abnormal,present,present,...,130.0,6.0,8.0,27.0,5479.0,4.4,poor,yes,3.375000,high
3,3.0,48.0,141.0,10.07,4.0,4.0,abnormal,abnormal,present,present,...,133.0,5.8,11.0,35.0,7817.0,3.2,poor,yes,3.181818,low
4,4.0,51.0,175.0,10.15,4.0,5.0,abnormal,abnormal,present,present,...,132.0,6.8,9.0,30.0,3055.0,3.9,poor,yes,3.333333,high

In [19]:
df_merged = pd.merge(df2 , df3, on='Patient ID', how='inner')
df_merged.head()

,Patient ID,Age_x,Blood Pressure_x,Urine Specific Gravity_x,Albumin in urine_x,Sugar in urine_x,RBC_x,Puss cells_x,Pus cells clumps_x,Bacteria_x,...,Sodium in blood_y,Potassium in blood_y,Hemoglobin_y,Packed corpuscular volume_y,WBC count_y,RBC count_y,Apetite_y,Chronic kidney failure_y,PVC_Hb ratio_y,Anemia risk_y
0,0,48,178,10.10,2.0,2,abnormal,abnormal,present,present,...,124.0,6.0,8.0,25.0,11319,3.8,poor,yes,3.125000,low
1,1,7,138,10.14,1.0,4,abnormal,abnormal,present,present,...,133.0,6.8,11.0,27.0,11018,2.9,poor,yes,2.454545,high
2,2,62,165,10.14,2.0,5,abnormal,abnormal,present,present,...,130.0,6.0,8.0,27.0,5479,4.4,poor,yes,3.375000,high
3,3,48,141,10.07,4.0,4,abnormal,abnormal,present,present,...,133.0,5.8,11.0,35.0,7817,3.2,poor,yes,3.181818,low
4,4,51,175,10.15,4.0,5,abnormal,abnormal,present,present,...,132.0,6.8,9.0,30.0,3055,3.9,poor,yes,3.333333,high

In [24]:
df_joined = df1.join(df3, lsuffix='_l', rsuffix='_r',  how='left')
df_joined.head()

,Patient ID_l,Age_l,Blood Pressure_l,Urine Specific Gravity_l,Albumin in urine_l,Sugar in urine_l,RBC_l,Puss cells_l,Pus cells clumps_l,Bacteria_l,...,Sodium in blood_r,Potassium in blood_r,Hemoglobin_r,Packed corpuscular volume_r,WBC count_r,RBC count_r,Apetite_r,Chronic kidney failure_r,PVC_Hb ratio_r,Anemia risk_r
190,190,6,130,10.09,4.0,2,abnormal,abnormal,present,present,...,122.0,5.70,6.0,24.0,11551.0,2.60,poor,yes,4.000000,high
2070,2070,6,112,10.22,0.0,1,abnormal,abnormal,absent,present,...,143.0,4.00,12.0,45.0,10893.0,5.50,poor,yes,3.750000,high
3548,3548,6,113,10.21,0.0,0,abnormal,abnormal,absent,present,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7982,7982,6,60,11.91,989.9,242,abnormal,abnormal,absent,present,...,139.1,4.80,10.0,30.9,4983.0,4.28,poor,yes,3.090000,low
9460,9460,6,60,12.78,20.0,199,abnormal,abnormal,absent,present,...,135.7,5.22,10.2,29.3,9652.0,4.30,poor,yes,2.872549,low